export const ThemeConfig = {
    default: {
        scrollBarTrack: '#424242',
        scrollBarThumb: '#EF5350',
        jobCardContainer: '#424242',
        jobCardBorder: '1px solid #616161',
        jobCardDataDisplayBorder: '1px solid #616161',
        jobCardSelectButtonBGSelected: '',
        jobCardSelectButtonBGUnselected: '#EF5350',
        jobCardSelectButtonBorderSelected: '2px solid #616161',
        jobCardSelectButtonBorderUnselected: '',
        jobCardSelectButtonTextColorSelected: '#616161',
        jobCardSelectButtonTextColorUnselected: '#e8e8e8',
        jobCardSelectButtonHoverBGSelected: '',
        jobCardSelectButtonHoverBGUnselected: '#F44336',
        NUIBackground: '#212121',
        settingsThemeDropdownBackground: '#424242',
        settingsThemeDropdownTextColor: '#e8e8e8',
        sidebarBackground: '#424242',
        sidebarBorderRight: '1px solid #EF5350',
        sidebarTabHoverBG: '#424242',
        sidebarTabSelectedBorderLeft: '4px solid #EF5350',
        sidebarTabSelectedBG: '#212121',
    },
    redline: {
        scrollBarTrack: '#424242',
        scrollBarThumb: '#EF5350',
        jobCardContainer: '#424242',
        jobCardBorder: '1px solid #616161',
        jobCardDataDisplayBorder: '1px solid #616161',
        jobCardSelectButtonBGSelected: '',
        jobCardSelectButtonBGUnselected: '#EF5350',
        jobCardSelectButtonBorderSelected: '2px solid #616161',
        jobCardSelectButtonBorderUnselected: '',
        jobCardSelectButtonTextColorSelected: '#616161',
        jobCardSelectButtonTextColorUnselected: '#e8e8e8',
        jobCardSelectButtonHoverBGSelected: '',
        jobCardSelectButtonHoverBGUnselected: '#F44336',
        NUIBackground: '#212121',
        settingsThemeDropdownBackground: '#424242',
        settingsThemeDropdownTextColor: '#e8e8e8',
        sidebarBackground: '#424242',
        sidebarBorderRight: '1px solid #EF5350',
        sidebarTabHoverBG: '#424242',
        sidebarTabSelectedBorderLeft: '4px solid #EF5350',
        sidebarTabSelectedBG: '#212121',
    },
    qbox: {
        scrollBarTrack: '#424242',
        scrollBarThumb: '#EF5350',
        jobCardContainer: '#424242',
        jobCardBorder: '1px solid #616161',
        jobCardDataDisplayBorder: '1px solid #616161',
        jobCardSelectButtonBGSelected: '',
        jobCardSelectButtonBGUnselected: '#FFEE58',
        jobCardSelectButtonBorderSelected: '2px solid #616161',
        jobCardSelectButtonBorderUnselected: '',
        jobCardSelectButtonTextColorSelected: '#616161',
        jobCardSelectButtonTextColorUnselected: '#212121',
        jobCardSelectButtonHoverBGSelected: '',
        jobCardSelectButtonHoverBGUnselected: '#FFD54F',
        NUIBackground: '#212121',
        settingsThemeDropdownBackground: '#424242',
        settingsThemeDropdownTextColor: '#e8e8e8',
        sidebarBackground: '#424242',
        sidebarBorderRight: '1px solid #FFEE58',
        sidebarTabHoverBG: '#424242',
        sidebarTabSelectedBorderLeft: '4px solid #FFEE58',
        sidebarTabSelectedBG: '#212121',
    }
}